language: python

python:
  - "3.8"

jobs:
  include:
    - stage: "Build Lab 2"
      name: "Run tests Lab 2"
      python: 3.8
      install:
        - cd ./Lab_2/
        - make install
      script: make test
    - stage: "Build Lab 3"
      name: "Run Djungo Server and test"
      python: 3.8
      install:
        - pipenv install
      before_install:
        - cd ./Lab_3/
        - chmod +x travis-build.sh
      script: ./travis-build.sh
    - stage: "Build Lab 4"
      name: "Build Docker Images"
      services:
        - docker
      install:
        - cd ./Lab_4/
      script:
        - docker build -t bodia1132/lab4:django-travis .
        - docker build -t bodia1132/lab4:monitor-travis --file Dockerfile.monitor . 
        - docker images
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$D_PASSWORD" | docker login -u "$D_USERNAME" --password-stdin; docker push bodia1132/lab4:django-travis; else echo "PR skip deploy"; fi
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$D_PASSWORD" | docker login -u "$D_USERNAME" --password-stdin; docker push bodia1132/lab4:monitor-travis; else echo "PR skip deploy"; fi
    - stage: "Build Lab 5"
      name: "Build and run Docker Images"
      services:
        - docker
      install:
        - cd ./Lab_5/
        - make app
        - make tests
      script:
        - make run
        - make test-app
        - echo "$D_PASSWORD" | docker login -u "$D_USERNAME" --password-stdin
        - make push
branches:
  only:
    - master
    - main
