version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vyacheslavbeltyukov/lab4:django
    container_name: django
    networks:
      - public
    ports:
      - 8000:8000
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.site
    image: vyacheslavbeltyukov/lab4:monitoring
    container_name: monitoring
    networks:
      - public

networks:
  public:
    driver: bridge